### PR TITLE
Fix max alowed value

### LINKED ISSUE #12: strconv.FormatInt base is 64? really?
panic info:

```panic: strconv: illegal AppendInt/FormatInt base [recovered]
	panic: strconv: illegal AppendInt/FormatInt base
```

code

```
	if c.Rows != 0 {
		req.Params["recaptcharows"] = strconv.FormatInt(int64(c.Rows), 64)
	}
	if c.Cols != 0 {
		req.Params["recaptchacols"] = strconv.FormatInt(int64(c.Cols), 64)
	}
	if c.PreviousId != 0 {
		req.Params["previousID"] = strconv.FormatInt(int64(c.PreviousId), 64)
	}
```

### PR DESCRIPTION
**Pull request by PBadicean**
I checked that the maximum allowed value for FormatUint will be 2 <= base <= 36
link to docs: https://github.com/golang/go/blob/master/src/strconv/itoa.go

Fixes #12

### CODE REVIEW

File: api2captcha.go [hunk 1]
```diff
@@ -426,7 +426,7 @@ func (req *Request) SetProxy(proxyType string, uri string) {
 }
 
 func (req *Request) SetSoftId(softId int) {
-	req.Params["soft_id"] = strconv.FormatInt(int64(softId), 64)
+	req.Params["soft_id"] = strconv.FormatInt(int64(softId), 36)
```
Comment (kratzky) [inline api2captcha.go:429]: Actually, the base should be `10`
All the parameters passed to FormatInt are just integers. So if we convert them with base set to 36 we'll get not the values we expect to get, for example:

```go
package main

import (
	"fmt"
	"strconv"
)

func main() {
	var softId int64 = 2832
	var PreviousId int64 = 73287895961
	
    arr := []int{36, 2, 16, 10}

    for i := 0; i < len(arr); i++ {
		fmt.Printf("softId with base %v is %v\n", arr[i], strconv.FormatInt(softId, arr[i]))
		fmt.Printf("PreviousId with base %v is %v\n", arr[i], strconv.FormatInt(PreviousId, arr[i]))
    }
}
```

And the output will be:

```text
softId with base 36 is 26o
PreviousId with base 36 is xo1pyft
softId with base 2 is 101100010000
PreviousId with base 2 is 1000100010000010011001000101110011001
softId with base 16 is b10
PreviousId with base 16 is 11104c8b99
softId with base 10 is 2832
PreviousId with base 10 is 73287895961
```
